version: 2
jobs:
  build:
    parallelism: 4
    working_directory: ~/circleci-sg
    resource_class: large
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - run: sudo apt-get install libapr1 openssl libxml2-utils
      - run:
          name: Versions
          command: 'uname -a;java -version;openssl version'
      - checkout
      - restore_cache:
          key: circleci-sg-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-sg-{{ checksum "pom.xml" }}
      - run: ./smoketest.sh
      - run:
          command: |
            ls -la
            pwd
            cd src/test/java
            TESTFILES=$(circleci tests glob "**/*Test*.java" | circleci tests split)
            TESTFILES2="$(circleci tests glob **/*Test*.java | circleci tests split)"
            echo $TESTFILES
            echo $TESTFILES2
            cd ~/circleci-sg
            mvn -Pcoverage verify mvn test -Dtest="$TESTFILES"
      #- run: mvn -Pcoverage verify mvn test -Dtest="com/floragunn/searchguard/HealthTests.java"
      - store_test_results:
          path: target/surefire-reports
      #- store_artifacts:
      #    path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
      - deploy:
          name: Maybe Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mvn -Pcoverage sonar:sonar -Dsonar.organization=floragunncom-github -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=https://sonarcloud.io
              mvn deploy -DskipTests -s settings.xml
              ./dev/scan_veracode.sh
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
